### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by kozora** [J3n5en/whmcs-alipay-python#2]
Traceback (most recent call last):
  File "alipay.py", line 2, in <module>
    from pyquery import PyQuery as pq
  File "/usr/local/lib/python2.7/dist-packages/pyquery/**init**.py", line 11, in <module>
    from .pyquery import PyQuery
  File "/usr/local/lib/python2.7/dist-packages/pyquery/pyquery.py", line 9, in <module>
    from lxml import etree
ImportError: No module named lxml

**Comment by J3n5en** [comment]
安装依赖。

**Comment by kozora** [comment]
pip install lxml ?
